version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    # N達o expor portas para o exterior
    expose:
      - "3306"  # Expor apenas para a rede interna (n達o para o exterior)

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    environment:
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    expose:
      - "3000"  # Expor apenas para a rede interna (n達o para o exterior)
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    expose:
      - "3000"  # Expor apenas para a rede interna (n達o para o exterior)
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"  # Expor porta 80 para o exterior
      - "443:443"  # Expor porta 443 para o exterior
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificados:/etc/nginx/certificados
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
